### PR TITLE
March2021

### PR DESCRIPTION
**Pull request by pab2163**
Paul additions to error interval rmd/slides, addressing #86 

Notes:

- Have not included content on multiple regression since we won't have time during the workshop. We could add later for reference though
- Not too detailed with code implementation -- maybe we can work on a better walkthrough for anyone who wants more specific implementation (rather than some of the more conceptual stuff we talk about) later?

### CODE REVIEW

**Review by monicathieu — APPROVED** [review]
My changes to Paul's additions are mainly syntax cleanliness, and sometimes pulling bullet points out into sentence form when it felt right.

My commits also include a full serve of the blogdown site. (I am using blogdown 1.1 I think!! Be aware! The serve and Rmd render functions are different now) I've created a landing page for the slides that iframes the slides in, and links directly to the slides html for to see them full size in another window. (That means the primary tutorial files that involve writing the site-knitter's R project path also have changes. Don't worry about those!)

Importantly, these should make up a framework such that small edits to the slides can be made in the future, but the current version can go up on the website now.

**Comment by emilynakka** [comment]
Not sure if you still need my approval as well, but I took a quick glance, and these changes look great to me! My only recommended addition might be to add this new tutorial to the "Additional Tutorials" section on the homepage, but I don't know anything about the `blogdown` update, so I'm worried that if I re-render the site without looking further into this I might break something. I can add this in the future. :)

**Review by emilynakka — APPROVED** [review]
Looks good on my end!

**Comment by monicathieu** [comment]
It should already show up on the "Additional Tutorials" section, thank you blogdown post list functionality!
I will go ahead and merge then, and you can do the ol gh-pages subtree push @emilynakka ?

**Comment by emilynakka** [comment]
It's on the Tutorials > Additional R Tutorials page, but the list at the bottom of the homepage (https://cu-psych-computing.github.io/cu-psych-comp-tutorial/#additional-tutorials) isn't automatically generated. No worries though—it's a really minor issue and I can update it later! Yes, I can do the gh-pages subtree push now. :)

**Comment by monicathieu** [comment]
Oh I totally forgot about that extra section on the homepage. The website is bigger than I can reason about now lolz, but if you could get it the next time you need to update the website that'd be great :)

**Pull request merged**
